;              
CREATE USER IF NOT EXISTS NMS SALT '31e0b99b3c3ca628' HASH 'cf94f10d41c50096e07e8abb3c5251fb0cfe4afbc97623ddaa8ff19ef757605e' ADMIN;           
CREATE MEMORY TABLE PUBLIC.SYSTEM_FALT_LOG(
    FALT_ID VARCHAR2(20) NOT NULL,
    SYS_GBN_CD VARCHAR2(20),
    ERR_GBN_CD VARCHAR2(20),
    ERR_MSG VARCHAR2(512),
    HOST VARCHAR2(256),
    MESSAGE VARCHAR2(1024),
    SMS_YN VARCHAR2(10),
    COLL_DTTI VARCHAR2(14)
); 
ALTER TABLE PUBLIC.SYSTEM_FALT_LOG ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(FALT_ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYSTEM_FALT_LOG;          
CREATE MEMORY TABLE PUBLIC.PROCESS_PROPERTY(
    PROPERTY_KEY VARCHAR2(40) NOT NULL,
    PROPERTY_VAL VARCHAR2(40) NOT NULL
); 
ALTER TABLE PUBLIC.PROCESS_PROPERTY ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(PROPERTY_KEY);              
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PROCESS_PROPERTY;         
CREATE MEMORY TABLE PUBLIC.SMS_PERN_USER_INFO(
    FALT_GBN_CD VARCHAR2(5) NOT NULL,
    USER_ID VARCHAR2(40) NOT NULL,
    USER_TEL_NO VARCHAR2(40) NOT NULL
);               
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.SMS_PERN_USER_INFO;       
CREATE INDEX PUBLIC.SMS_PERN_USER_INFO_IDX1 ON PUBLIC.SMS_PERN_USER_INFO(FALT_GBN_CD);         
CREATE MEMORY TABLE PUBLIC.PROCESS_STATUS_DATA(
    COLL_DTTI VARCHAR2(14) DEFAULT '197001010000' SELECTIVITY 66,
    PROC_NAME VARCHAR2(20) SELECTIVITY 100,
    PROC_CODE VARCHAR2(20) SELECTIVITY 100,
    PROC_STAT VARCHAR2(10) SELECTIVITY 33,
    PROC_INDX VARCHAR2(20) DEFAULT '' SELECTIVITY 33,
    PID_INFO VARCHAR2(10) SELECTIVITY 100,
    CPU_INFO VARCHAR2(10) SELECTIVITY 33,
    MEM_INFO VARCHAR2(10) SELECTIVITY 33,
    RSS_INFO VARCHAR2(10) SELECTIVITY 100,
    DEFUNCT_CNT NUMBER SELECTIVITY 33,
    JOB_STT_TIME VARCHAR2(14) SELECTIVITY 33,
    JOB_END_TIME VARCHAR2(14) SELECTIVITY 33
);      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.PROCESS_STATUS_DATA;      
CREATE INDEX PUBLIC.PROCESS_STATUS_DATA_IDX1 ON PUBLIC.PROCESS_STATUS_DATA(PROC_CODE, PROC_INDX);              
CREATE MEMORY TABLE PUBLIC.TARGET_PROCESS_INFO(
    PROC_NO NUMBER SELECTIVITY 100,
    PROC_CODE VARCHAR2(20) SELECTIVITY 100,
    PROC_NAME VARCHAR2(20) SELECTIVITY 100,
    PROC_INDX VARCHAR2(20) SELECTIVITY 50,
    HOST_IP VARCHAR2(100) SELECTIVITY 100,
    HOST_ID VARCHAR2(100) SELECTIVITY 100,
    HOST_PW VARCHAR2(100) SELECTIVITY 100,
    PROMPT VARCHAR2(100) SELECTIVITY 50,
    WATCH_YN VARCHAR2(3) SELECTIVITY 50,
    SMS_SEND_CNT NUMBER DEFAULT 0 SELECTIVITY 50,
    WATCH_HANG VARCHAR2(2) DEFAULT 'Y',
    WATCH_DOWN VARCHAR2(2) DEFAULT 'Y'
);           
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TARGET_PROCESS_INFO;      
CREATE INDEX PUBLIC.TARGET_PROCESS_INFO_IDX1 ON PUBLIC.TARGET_PROCESS_INFO(PROC_CODE, PROC_INDX);              
CREATE MEMORY TABLE PUBLIC.MMI_STATUS(
    PROC_CODE VARCHAR(20) NOT NULL,
    PROC_INDX VARCHAR(20) NOT NULL,
    PROC_EXCHANGE VARCHAR(50),
    PROC_STAT VARCHAR(10) DEFAULT 'down' NOT NULL,
    WEIGHT NUMBER(2) DEFAULT 0 NOT NULL,
    HIT_CNT NUMBER(5) DEFAULT 0 NOT NULL,
    COLL_DTTI VARCHAR2(14),
    TARGET VARCHAR2(100)
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MMI_STATUS;               
CREATE UNIQUE INDEX PUBLIC.PK_TABLE ON PUBLIC.MMI_STATUS(PROC_CODE, PROC_INDX);
