;              
CREATE USER IF NOT EXISTS NMS SALT '485ce6245c166ccb' HASH '11e36ec8af76055a4818fafbbc6f81d77e6da30f5af4f6a22d1d915debe8a8ed' ADMIN;


CREATE MEMORY TABLE PUBLIC.SYSTEM_FALT_LOG(
    FALT_ID      VARCHAR2(20) NOT NULL PRIMARY KEY,
    SYS_GBN_CD   VARCHAR2(256),
    ERR_GBN_CD   VARCHAR2(256),
    ERR_MSG      VARCHAR2(256),
    HOST         VARCHAR2(256),
    MESSAGE      VARCHAR2(512),
    SMS_YN       VARCHAR2(3),
    COLL_DTTI    VARCHAR2(14)
);


CREATE MEMORY TABLE PUBLIC.PROCESS_PROPERTY(
    PROPERTY_KEY VARCHAR2(40) NOT NULL PRIMARY KEY,
    PROPERTY_VAL VARCHAR2(40) NOT NULL
);


CREATE MEMORY TABLE PUBLIC.SMS_PERN_USER_INFO(
    FALT_GBN_CD VARCHAR2(5) NOT NULL,
    USER_ID VARCHAR2(40) NOT NULL,
    USER_TEL_NO VARCHAR2(40) NOT NULL
);
CREATE INDEX PUBLIC.SMS_PERN_USER_INFO_IDX1 ON PUBLIC.SMS_PERN_USER_INFO(FALT_GBN_CD);


CREATE MEMORY TABLE PUBLIC.SMS_AUTH_USER_INFO(
    FALT_GBN_CD  VARCHAR2(5) NOT NULL,
    AUTH_CD  VARCHAR2(40) NOT NULL
);
CREATE INDEX PUBLIC.SMS_AUTH_USER_INFO_IDX1 ON PUBLIC.SMS_AUTH_USER_INFO(FALT_GBN_CD);


CREATE MEMORY TABLE PUBLIC.PROCESS_STATUS_DATA(
    COLL_DTTI     VARCHAR2(14) NOT NULL DEFAULT '197001010000',
    PROC_CODE     VARCHAR2(20) NOT NULL,
    PROC_NAME     VARCHAR2(20) NOT NULL,
    PROC_STAT     VARCHAR2(10),
    PROC_INDX     VARCHAR2(20) NOT NULL DEFAULT '',
    PID_INFO      VARCHAR2(10),
    CPU_INFO      VARCHAR2(10),
    MEM_INFO      VARCHAR2(10),
    RSS_INFO      VARCHAR2(10),
    DEFUNCT_CNT      VARCHAR2(10),
    JOB_STT_TIME  VARCHAR2(14),
    JOB_END_TIME  VARCHAR2(14)
);

-- 1 +/- SELECT COUNT(*) FROM PUBLIC.FPING_OUTPUT_RAW;         
CREATE INDEX PUBLIC.PROCESS_STATUS_DATA_IDX1 ON PUBLIC.PROCESS_STATUS_DATA(PROC_NAME, PROC_INDX);

CREATE MEMORY TABLE PUBLIC.TARGET_PROCESS_INFO(
    PROC_NO      NUMBER,
    PROC_CODE    VARCHAR2(20),
    PROC_NAME    VARCHAR2(20),
    PROC_INDX    VARCHAR2(20),
    HOST_IP      VARCHAR2(50),
    HOST_ID      VARCHAR2(100),
    HOST_PW      VARCHAR2(100),
    PROMPT       VARCHAR2(100),
    SMS_SEND_CNT NUMBER(3)
);

-- 1 +/- SELECT COUNT(*) FROM PUBLIC.FPING_OUTPUT_RAW;         
CREATE INDEX PUBLIC.TARGET_PROCESS_INFO_IDX1 ON PUBLIC.TARGET_PROCESS_INFO(PROC_NAME, PROC_INDX);

CREATE MEMORY TABLE PUBLIC.MMI_STATUS(
    PROC_NAME    VARCHAR2(20),
    PROC_INDX    VARCHAR2(20),
    PROC_DOWN    VARCHAR2(20),
    HIT_CNT      NUMBER
);

-- 1 +/- SELECT COUNT(*) FROM PUBLIC.FPING_OUTPUT_RAW;         
CREATE INDEX PUBLIC.MMI_STATUS_IDX1 ON PUBLIC.MMI_STATUS(PROC_NAME, PROC_INDX);
